
export default {
  BRIDGES_LOADING: "BRIDGES_LOADING",
  BRIDGES_LOADED: "BRIDGES_LOADED",
  BRIDGE_AUTHENTICATING: "BRIDGE_AUTHENTICATING",
  BRIDGE_AUTHENTICATED: "BRIDGE_AUTHENTICATED",
  BRIDGE_SELECTED: "BRIDGE_SELECTED",
  LIGHTS_LOADING: "LIGHTS_LOADING",
  LIGHTS_LOADED: "LIGHTS_LOADED",
  LIGHT_UPDATING: "LIGHT_UPDATING",
  LIGHT_UPDATED: "LIGHT_UPDATED",
};
