
export default {
  BRIDGES_LOADING: "BRIDGES_LOADING",
  BRIDGES_LOADED: "BRIDGES_LOADED",
  BRIDGE_AUTHENTICATING: "BRIDGE_AUTHENTICATING",
  BRIDGE_AUTHENTICATED: "BRIDGE_AUTHENTICATED",
  BRIDGE_SELECTED: "BRIDGE_SELECTED",
};
